services:
  db:
    container_name: "db"
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - custom
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: "redis"
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - custom
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  app:
    container_name: "booking_app"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - custom
    environment:
      - MODE=PROD
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery:
    container_name: "celery_worker"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A app.tasks.celery worker --loglevel=info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - custom
    environment:
      - MODE=PROD
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "celery", "-A", "app.tasks.celery", "inspect", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 15s

  flower:
    container_name: "flower"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A app.tasks.celery flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      redis:
        condition: service_healthy
      celery:
        condition: service_healthy
    networks:
      - custom
    environment:
      - MODE=PROD
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

networks:
  custom:
    driver: bridge

volumes:
  postgres_data:
  redis_data: